import { StyleSheet } from "react-native";

export const COLORS = {
    primary: "#6a453b", // Coklat Tua
    secondary: "#ceaa7a", // Coklat Muda
    background: "#e9e2ce", // Krem
    accent1: "#7399bd", // Biru Muda
    accent2: "#1c477f", // Biru Tua
    accent3: "#e67e22", // Oranye
    accent4: "#bd671b", // Oranye Tua
    white: "#FFFFFF",
    gray: "#A9A9A9",
};

export const FONTS = {
    regular: "Urbanist-Regular",
    bold: "Urbanist-Bold",
    oldStandardRegular: "OldStandardTT-Regular",
    oldStandardBold: "OldStandardTT-Bold",
    oldStandardItalic: "OldStandardTT-Italic",
};

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#FFFFFF",
        paddingHorizontal: 25,
        justifyContent: "center",
    },
    logo: {
        height: 200,
        resizeMode: "contain",
        alignSelf: "center",
        marginBottom: 20,
    },
    title: {
        fontFamily: FONTS.regular,
        fontSize: 20,
        color: "#21262E",
        textAlign: "center",
        marginBottom: 40,
    },
    input: {
        fontFamily: FONTS.bold,
        backgroundColor: "#F8F9FA",
        borderWidth: 1,
        borderColor: "#E5E7EB",
        borderRadius: 20,
        padding: 15,
        fontSize: 16,
        marginBottom: 15,
        color: "#21262E",
    },
    passwordContainer: {
        position: "relative",
        marginBottom: 15,
    },
    passwordInput: {
        fontFamily: FONTS.bold,
        backgroundColor: "#F8F9FA",
        borderWidth: 1,
        borderColor: "#E5E7EB",
        borderRadius: 20,
        padding: 15,
        paddingRight: 50,
        fontSize: 16,
        color: "#21262E",
    },
    eyeButton: {
        position: "absolute",
        right: 15,
        top: "50%",
        transform: [{ translateY: -10 }],
        padding: 5,
    },
    button: {
        backgroundColor: COLORS.primary,
        padding: 15,
        borderRadius: 20,
        alignItems: "center",
        marginVertical: 10,
    },
    buttonText: {
        fontFamily: FONTS.bold,
        color: COLORS.white,
        fontSize: 16,
    },
    dividerText: {
        fontFamily: FONTS.regular,
        color: "#95A5A6",
        textAlign: "center",
        marginVertical: 20,
        marginHorizontal: 12,
    },
    socialButton: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#FFFFFF",
        borderWidth: 1,
        borderColor: "#E5E7EB",
        padding: 15,
        borderRadius: 20,
    },
    socialButtonText: {
        fontFamily: FONTS.bold,
        color: "#21262E",
        fontSize: 16,
        marginLeft: 10,
    },
    linkText: {
        fontFamily: FONTS.regular,
        marginTop: 25,
        color: "#21262E",
        textAlign: "center",
    },
    linkBold: {
        fontFamily: FONTS.bold,
        color: "#1c477f",
    },
    icon: {
        height: 24,
        width: 24,
    },
    linedivider: { flex: 1, height: 1, backgroundColor: "#95A5A6" },

    // Dashboard Styles
    NavMenuSafeArea: {
        flex: 1,
        backgroundColor: COLORS.primary,
    },

    // Enhanced Header Styles
    topHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingHorizontal: 20,
        paddingTop: 15,
        paddingBottom: 10,
    },
    headerLeft: {
        flex: 1,
    },
    headerActions: {
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
    },
    coinRewardButton: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "rgba(206, 170, 122, 0.2)",
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: COLORS.secondary,
    },
    headerCoinIcon: {
        width: 18,
        height: 18,
        marginRight: 6,
    },
    headerCoinText: {
        fontFamily: FONTS.bold,
        fontSize: 13,
        color: COLORS.white,
    },
    welcomeText: {
        fontFamily: FONTS.regular,
        fontSize: 14,
        color: COLORS.secondary,
        opacity: 0.8,
    },
    userNameText: {
        fontFamily: FONTS.bold,
        fontSize: 20,
        color: COLORS.white,
        marginTop: 2,
    },
    notificationButton: {
        position: "relative",
        padding: 8,
        borderRadius: 20,
        backgroundColor: "rgba(255, 255, 255, 0.1)",
    },
    notificationBadge: {
        position: "absolute",
        top: 2,
        right: 2,
        backgroundColor: "#ef4444",
        borderRadius: 8,
        minWidth: 16,
        height: 16,
        justifyContent: "center",
        alignItems: "center",
    },
    notificationBadgeText: {
        color: COLORS.white,
        fontSize: 10,
        fontFamily: FONTS.bold,
    },
    userProfileSection: {
        flexDirection: "row",
        alignItems: "center",
        flex: 1,
    },
    userInfo: {
        marginLeft: 12,
        flex: 1,
    },
    userStatusText: {
        fontFamily: FONTS.regular,
        fontSize: 12,
        color: COLORS.secondary,
        marginTop: 2,
    },
    coinRewardContainer: {
        backgroundColor: "rgba(255, 255, 255, 0.15)",
        borderRadius: 12,
        padding: 12,
        alignItems: "center",
        minWidth: 80,
        borderWidth: 1,
        borderColor: "rgba(255, 255, 255, 0.2)",
    },
    coinHeader: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 4,
    },
    rewardText: {
        fontFamily: FONTS.regular,
        fontSize: 10,
        color: COLORS.secondary,
        marginLeft: 4,
    },
    rewardSubtext: {
        fontFamily: FONTS.regular,
        fontSize: 9,
        color: COLORS.secondary,
        marginTop: 2,
        opacity: 0.8,
    },
    filterButton: {
        padding: 8,
        borderRadius: 15,
        backgroundColor: COLORS.background,
    },
    dashboardContainer: {
        flex: 1,
        paddingHorizontal: 15,
        backgroundColor: COLORS.white,
        paddingTop: 20,
        paddingBottom: 10,
    },
    contentContainer: {
        backgroundColor: COLORS.background,
        elevation: 1,
        marginBottom: 25,
        padding: 15,
        borderRadius: 10,
    },
    dashboardHeader: {
        backgroundColor: COLORS.primary,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 20,
        paddingVertical: 15,
    },
    dashboardHeaderTitle: {
        fontFamily: FONTS.bold,
        fontSize: 28,
        color: COLORS.white,
    },
    searchBarContainer: {
        flexDirection: "row",
        alignItems: "center",
        borderColor: "rgba(255, 255, 255, 0.3)",
        borderWidth: 1,
        marginHorizontal: 15,
        marginTop: 10,
        paddingHorizontal: 15,
        borderRadius: 25,
        marginBottom: 20,
        backgroundColor: COLORS.white,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    searchIcon: {
        marginRight: 12,
    },
    searchBarWrapper: {
        paddingHorizontal: 5,
    },
    searchBarInput: {
        flex: 1,
        fontSize: 14,
        color: COLORS.primary,
        fontFamily: FONTS.regular,
        paddingVertical: 12,
    },
    headerButton: {
        padding: 8,
    },
    headerRightIcons: {
        flexDirection: "row",
        gap: 5,
    },
    userGreeting: {
        backgroundColor: "rgba(233, 226, 206, 0.15)",
        borderRadius: 15,
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 20,
        paddingVertical: 18,
        marginVertical: 15,
        marginHorizontal: 15,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    userAvatar: {
        width: 50,
        height: 50,
        borderRadius: 25,
        marginRight: 15,
        borderWidth: 3,
        borderColor: COLORS.secondary,
    },
    greetingText: {
        fontFamily: FONTS.bold,
        fontSize: 16,
        color: COLORS.white,
    },
    coinIcon: {
        width: 20,
        height: 20,
        marginRight: 2,
    },
    pointsBadge: {
        backgroundColor: COLORS.accent2,
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 15,
        flexDirection: "row",
    },
    pointsText: {
        color: COLORS.white,
        fontSize: 14,
        fontFamily: FONTS.bold,
        textAlign: "center",
    },
    // Professional Features Menu Styles
    professionalFeaturesContainer: {
        backgroundColor: COLORS.background,
        marginBottom: 25,
        // marginHorizontal: 15,
        borderRadius: 16,
        padding: 10,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        elevation: 4,
    },
    professionalFeaturesGrid: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "flex-start",
    },
    professionalFeatureButton: {
        alignItems: "center",
        flex: 1,
        paddingVertical: 8,
    },
    professionalFeatureIconWrapper: {
        width: 56,
        height: 56,
        borderRadius: 14,
        alignItems: "center",
        justifyContent: "center",
        marginHorizontal: 4,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.15,
        shadowRadius: 6,
        elevation: 5,
        borderWidth: 1,
        borderColor: "rgba(255, 255, 255, 0.2)",
    },
    professionalFeatureIcon: {
        width: 32,
        height: 32,
        resizeMode: "contain",
    },
    professionalFeatureSpecialBackground: {
        borderWidth: 2,
        borderColor: "#e67e22",
        shadowColor: "#e67e22",
        shadowOpacity: 0.3,
    },
    professionalFeatureNewBadge: {
        position: "absolute",
        top: -6,
        right: -6,
        backgroundColor: "#e74c3c",
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 10,
        borderWidth: 2,
        borderColor: COLORS.white,
    },
    professionalFeatureNewBadgeText: {
        color: COLORS.white,
        fontSize: 9,
        fontFamily: FONTS.bold,
        letterSpacing: 0.5,
    },
    professionalFeatureLabel: {
        fontSize: 10,
        textAlign: "center",
        marginTop: 5,
        color: COLORS.primary,
        fontFamily: FONTS.bold,
        lineHeight: 16,
        maxWidth: 80,
    },
    historySection: {
        marginBottom: 25,
    },
    sectionHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 15,
    },
    sectionTitle: {
        fontFamily: FONTS.bold,
        fontSize: 22,
        color: COLORS.primary,
    },
    viewAllLink: {
        color: COLORS.accent2,
        fontFamily: FONTS.bold,
        fontSize: 16,
    },
    historyGrid: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "space-between",
    },
    historyCard: {
        backgroundColor: COLORS.white,
        borderRadius: 15,
        marginBottom: 15,
        width: "48%",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.12,
        shadowRadius: 6,
        elevation: 4,
    },
    historyCardImage: {
        width: "100%",
        height: 120,
        borderTopLeftRadius: 15,
        borderTopRightRadius: 15,
    },
    historyCardTextContainer: {
        padding: 12,
    },
    historyCardTitle: {
        fontFamily: FONTS.bold,
        fontSize: 13,
        color: COLORS.primary,
        lineHeight: 18,
    },
    bottomNav: {
        backgroundColor: COLORS.primary,
        flexDirection: "row",
        justifyContent: "space-around",
        position: "relative",
        paddingVertical: 10,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: -2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 8,
    },
    navItem: {
        alignItems: "center",
        width: "25%",
        paddingVertical: 10,
    },
    navIconContainer: {
        justifyContent: "center",
        alignItems: "center",
    },
    navIconActive: {
        width: 24,
        height: 24,
        tintColor: COLORS.white,
    },
    navIcon: {
        width: 24,
        height: 24,
        tintColor: COLORS.secondary,
    },
    navIndicator: {
        position: "absolute",
        top: 0,
        left: 0,
        width: "25%",
        height: 3,
        backgroundColor: COLORS.secondary,
        borderBottomLeftRadius: 3,
        borderBottomRightRadius: 3,
    },
    navLabel: {
        fontSize: 12,
        marginTop: 4,
        fontFamily: FONTS.regular,
    },
    navLabelActive: {
        color: COLORS.white,
        fontFamily: FONTS.bold,
    },
    navLabelInactive: {
        color: COLORS.secondary,
    },
});

export default styles;
